name: workflow
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        uses: mooyoul/tslint-actions@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'
          
      - name: Build
        run: npm run build
      
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
